spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST}
      port: ${SPRING_DATA_REDIS_PORT}
      password: ${SPRING_DATA_REDIS_PASSWORD}
      database: ${SPRING_DATA_REDIS_DATABASE:0}
      timeout: ${SPRING_DATA_REDIS_TIMEOUT:30000ms}
      lettuce:
        pool:
          max-active: ${SPRING_DATA_REDIS_LETTUCE_POOL_MAX_ACTIVE:8}
          max-wait: ${SPRING_DATA_REDIS_LETTUCE_POOL_MAX_WAIT:-1ms}
          max-idle: ${SPRING_DATA_REDIS_LETTUCE_POOL_MAX_IDLE:8}
          min-idle: ${SPRING_DATA_REDIS_LETTUCE_POOL_MIN_IDLE:0}

jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION:86400000}

file:
  upload:
    base-path: ${FILE_UPLOAD_BASE_PATH}
    base-url: ${FILE_UPLOAD_BASE_URL}
